# Generated by Django 3.2.9 on 2021-11-19 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0002_auto_20211118_2324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='destiny_origin',
            new_name='destiny_account',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='account_origin',
            new_name='origin_account',
        ),
    ]
